"""
Django settings for queuemanager project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from pathlib import Path
import os
import json
import decouple

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = decouple.config('SECRET_KEY', default='')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = decouple.config("DEBUG", default=False, cast=bool)
QUEUE_URL = decouple.config('QUEUE_URL', default='https://no.queue.url.configured')
QUEUE_URL_HOST = decouple.config('QUEUE_URL_HOST', default='no.queue.host.url.configured')
QUEUE_DOMAIN = decouple.config('QUEUE_DOMAIN', default='no.queue.domain.configured')

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = []
if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    # ALLOWED_HOSTS = env('ALLOWED_HOSTS', [])
    ALLOWED_HOSTS_STRING = decouple.config("ALLOWED_HOSTS", default='[]', )    
    ALLOWED_HOSTS = json.loads(str(ALLOWED_HOSTS_STRING))

CORS_ALLOW_ALL_ORIGINS=True
CORS_ORIGIN_ALLOW_ALL = True
# Application definition

INSTALLED_APPS = [
    
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    # 'django_cron',
    'django_extensions',
    'django_site_queue',
    'webtemplate_dbca',
    'wagov_utils',
    'appmonitor_client'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django_site_queue.custom_sessionmiddleware.DisableSessionMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'wagov_utils.components.middleware.no_signal_login_middleware.JSONAuthMiddleware',
    'wagov_utils.components.json_auth.auth2_sso_middleware.SSOLoginMiddleware',
    'django_site_queue.middleware.CacheControl',
    # 'django_site_queue.ipblock_middleware.IPMonitor',
]
SILENCED_SYSTEM_CHECKS = ["admin.E410"]


AUTHENTICATION_BACKENDS = (
            # 'django.contrib.auth.backends.ModelBackend',
            #'wagov_utils.components.json_auth.json_auth_backend.JSONAuthBackend',
            'wagov_utils.components.json_auth.auth_middleware_backend.JSONFileOnlyBackend',
)

ROOT_URLCONF = 'queuemanager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_site_queue.context_processors.variables',
            ],
        },
    },
]

WSGI_APPLICATION = 'queuemanager.wsgi.application'

# JSON_AUTH_FILE="./secrets/users.json"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db/db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.dummy"  # raises error if ORM is used
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Australia/Perth'

USE_I18N = True

USE_L10N = True

USE_TZ = True

CRON_CLASSES = [
    'appmonitor_client.cron.CronJobAppMonitorClient',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
VERSION_NO = "2.02"

GIT_COMMIT_HASH = os.popen(f"cd {BASE_DIR}; git log -1 --format=%H").read()
GIT_COMMIT_DATE = os.popen(f"cd {BASE_DIR}; git log -1 --format=%cd").read()
CSRF_TRUSTED_ORIGINS_STRING = decouple.config("CSRF_TRUSTED_ORIGINS", default='[]')
CSRF_TRUSTED_ORIGINS = json.loads(str(CSRF_TRUSTED_ORIGINS_STRING))

JSON_AUTH_FILE = BASE_DIR / "secrets" / "users.json"
JSON_AUTH_USERNAME_FIELD = "email"  # optional

# --- Sessions: use signed cookies (no DB tables required) ---
# SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"
AUTH_DB_FREE = True

SESSION_ENGINE = 'django.contrib.sessions.backends.file'
SESSION_FILE_PATH = decouple.config('SESSION_FILE_PATH', default='./session_store/')
DIRECTORY_SESSION_LIMIT = decouple.config("DIRECTORY_SESSION_LIMIT", default=100)
DIRECTORY_FOLDER_LIMIT = decouple.config("DIRECTORY_FOLDER_LIMIT", default=40)

SCRIPT_EXEMPT_KEY = decouple.config('SCRIPT_EXEMPT_KEY', default=None)
QUEUE_STORE_DB = decouple.config('QUEUE_STORE_DB', default='./db/json/')
JSON_AUTH_STORE_DB = decouple.config('JSON_AUTH_STORE_DB', default='./db/json/')
SESSION_EXPIRY_SSO = 3600

ENABLE_DJANGO_LOGIN=decouple.config("ENABLE_DJANGO_LOGIN", default=False, cast=bool)