# Generated by Django 3.1.5 on 2021-01-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site_queue', '0004_sitequeuemanager_browser_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteQueueManagerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=256)),
                ('group_unique_key', models.CharField(max_length=40)),
                ('session_total_limit', models.IntegerField(default=2)),
                ('session_limit_seconds', models.IntegerField(default=20)),
                ('cpu_percentage_limit', models.IntegerField(default=60)),
                ('idle_limit_seconds', models.IntegerField(default=15)),
                ('active_session_url', models.CharField(max_length=1024)),
                ('waiting_queue_enabled', models.BooleanField(default=False)),
                ('queue_domain', models.CharField(max_length=256)),
                ('queue_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sitequeuemanager',
            options={'managed': True},
        ),
    ]
