# Generated by Django 3.1.5 on 2021-01-15 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_site_queue', '0005_auto_20210115_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitequeuemanager',
            name='queue_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='django_site_queue.sitequeuemanagergroup'),
            preserve_default=False,
        ),
    ]
