# Generated by Django 3.1.5 on 2021-01-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site_queue', '0007_auto_20210120_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitequeuemanagergroup',
            name='ping_url_current',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='sitequeuemanagergroup',
            name='ping_url_limit',
            field=models.FloatField(default=5),
        ),
    ]
