# Generated by Django 3.1.5 on 2021-01-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site_queue', '0008_auto_20210120_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitequeuemanagergroup',
            name='time_left_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
