# Generated by Django 3.1.5 on 2021-01-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site_queue', '0009_sitequeuemanagergroup_time_left_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitequeuemanagergroup',
            name='browser_inactivity_redirect',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='sitequeuemanagergroup',
            name='browser_inactivity_timeout',
            field=models.IntegerField(default=60),
        ),
    ]
