# Generated by Django 3.1.5 on 2021-03-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site_queue', '0010_auto_20210121_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitequeuemanagergroup',
            name='browser_inactivity_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
