# Generated by Django 3.1.5 on 2022-10-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site_queue', '0011_sitequeuemanagergroup_browser_inactivity_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitequeuemanagergroup',
            name='custom_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
