# Generated by Django 3.1.5 on 2022-11-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site_queue', '0014_auto_20221013_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitequeuemanagergroup',
            name='custom_message',
            field=models.TextField(blank=True, help_text='Short message to explain the reason for the waiting queue', max_length=650, null=True),
        ),
    ]
