# Generated by Django 3.1.5 on 2022-11-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site_queue', '0015_auto_20221107_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitequeuemanagergroup',
            name='show_queue_position',
            field=models.BooleanField(default=False),
        ),
    ]
