# Generated by Django 3.1.5 on 2022-11-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site_queue', '0016_sitequeuemanagergroup_show_queue_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitequeuemanagergroup',
            name='max_queue_session_limit',
            field=models.IntegerField(default=1000),
        ),
    ]
