# Generated by Django 3.1.5 on 2022-11-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site_queue', '0017_sitequeuemanagergroup_max_queue_session_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitequeuemanagergroup',
            name='max_queue_url_redirect',
            field=models.CharField(default='', max_length=256),
        ),
    ]
