# Generated by Django 3.2.23 on 2024-01-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site_queue', '0018_sitequeuemanagergroup_max_queue_url_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitequeuemanagergroup',
            name='template_header_key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
