# Generated by Django 3.2.23 on 2024-01-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site_queue', '0019_sitequeuemanagergroup_template_header_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitequeuemanagergroup',
            name='browser_inactivity_redirect',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
