# Generated by Django 3.2.23 on 2024-01-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site_queue', '0020_alter_sitequeuemanagergroup_browser_inactivity_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitequeuemanagergroup',
            name='active_session_url_label',
            field=models.CharField(default='Click Here', max_length=1024),
        ),
    ]
