# Generated by Django 3.2.23 on 2024-01-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site_queue', '0021_sitequeuemanagergroup_active_session_url_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitequeuemanagergroup',
            name='active_session_url_label',
            field=models.CharField(default='This Site', max_length=1024),
        ),
    ]
